services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file: docker_env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432