spring:
  #Config database
  datasource:
    plataform: postgres
    url: jdbc:postgresql://postgres:5432/farm_control
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

  #Dev-tools
  devtools:
    restart:
      poll-interval: 20s
      quiet-period: 10s

#JWT
jwt:
  secret: secret
  expiration: 1800000