spring:
  #Config database
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/farm_control
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

  #Dev-tools
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

#JWT
jwt:
  secret: L2ZNrKdwnpt9SAU9k2uUZAQLvfsV8TZXVD32qwg8dfssnUGsoVjs
  expiration: 1800000